#!/bin/bash

# Name and location of this script:
#
# /usr/bin/update-theme-package
#
# This script is part of the desktop-theme-package. It finishes the 
# installation of that package.
#
# It is supposed to be run as root.
# 
# Description:
# 
# update-desktop-theme [-i]
#               choose and install a theme for all users.
#
# update-desktop-theme [-r]
#               remove all changes and reinstall the Debian default 
#               theme. Use this before you uninstall the desktop-
#               theme-package.
# 
# Please see:
#
# /usr/share/desktop-theme-kit/readme/readme.txt
#
# for more information about this package and how to use your own 
# artwork.
#
# Copyright (C) 2012, 2013 Ulrich Hansen <uhansen@debianart.org>
#               2012 Ronoaldo JLP <ronoaldo@gmail.com>


# Stop on failures
set -e

THEME=kit
PACKAGE=desktop-theme-package
ARTWORK_FOLDER=desktop-themes
DEBIAN_DEFAULT=joy


# ------------
# Choose theme
#-------------


choose_theme() {
echo -e "\nHere's a list of all themes present in /usr/share/images/desktop-themes. \nPlease type the name of the new theme you wish to install.\n"
cd /usr/share/images/$ARTWORK_FOLDER/
for i in $(ls -d */); do echo ${i%%/}; done
echo -e "\nOr type 'a' to just activate the default theme.\n"
read ANSWER
    
    if [ "$ANSWER" == "a" ]; then
    echo "No new theme chosen. Activating the existing theme."
    else

    if [ -f /usr/share/images/$ARTWORK_FOLDER/$ANSWER/wallpaper.png ]; then
    cp /usr/share/images/$ARTWORK_FOLDER/$ANSWER/wallpaper.png  /usr/share/desktop-theme-$THEME/backgrounds/$THEME-wallpaper.png;
    echo "The wallpaper for the theme $ANSWER has been installed."

    else
    echo "No wallpaper found. Please make sure there is a file /usr/share/images/$ARTWORK_FOLDER/$ANSWER/wallpaper.png"
    fi

    if [ -f /usr/share/images/$ARTWORK_FOLDER/$ANSWER/login.png ]; then
        cp /usr/share/images/$ARTWORK_FOLDER/$ANSWER/login.png  /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png;

    echo "The login-background for theme $ANSWER has been installed."

    else
    echo "No login-background found. Please make sure there is a file /usr/share/images/$ARTWORK_FOLDER/$ANSWER/login.png"
    fi

    if [ -f /usr/share/images/$ARTWORK_FOLDER/$ANSWER/grub.png ]; then
        cp /usr/share/images/$ARTWORK_FOLDER/$ANSWER/grub.png  /usr/share/desktop-theme-$THEME/grub/$THEME-grub.png;
 
    echo "The Grub2 picture for the theme $ANSWER has been installed."

    else
    echo "No picture for Grub2 found. Please make sure there is a file /usr/share/images/$ARTWORK_FOLDER/$ANSWER/grub.png"
    fi

    fi
}


# -------
# INSTALL
# -------

# 1. Gnome Wallpaper
#
# 1.1 Clear cache
#
# Until the cache in the users home directory has been cleared, the 
# user will see the old wallpaper.


clear_wallpaper_cache_as_root() {
    rm -f /home/*/.cache/wallpaper/*  2>/dev/null;
    rm -f -r /home/*/.kde/cache-debian/*
}

# 1.2 Initialize the wallpaper
#
# The new theme has to be initialized once through gsettings, even 
# though it uses the same alternative as the old one.
#
# To do this for all users, we put a script into the gnome autostart
# folder. The script is executed only once. So the users stay free 
# to choose individual wallpapers and our desktop-theme won't keep 
# popping up every time Gnome is started.

set_gnome_wallpaper_as_root() {
    OUT="$(mktemp)"
    cat <<EOF > $OUT
[Desktop Entry]
Type=Application
Name=Desktop Theme Package Installer
Comment=Activates the wallpaper in Gnome. Runs only once. Puts an .id file into the home directories to prevent it from running every time Gnome is started.
Exec=/bin/sh -c "/usr/bin/test -f ~/.$PACKAGE.id || /usr/bin/gsettings set org.gnome.desktop.background picture-uri file:///usr/share/images/desktop-base/desktop-background; /usr/bin/test -f ~/.$PACKAGE.id || /bin/touch ~/.$PACKAGE.id"
OnlyShowIn=GNOME;
EOF
    mv $OUT /etc/xdg/autostart/$PACKAGE.desktop;
    chmod 644 /etc/xdg/autostart/$PACKAGE.desktop;
    find /home -name ".$PACKAGE.id" -delete
}


# 2. KDE

# 2.1 Wallpaper
#
# The Debian Wheezy theme "Joy" is "hardcoded" as KDE wallpaper and
# can't be changed by using alternatives. This is resolved in Jessy 
# (see desktop-base Bug#690731)
# 
# Until then we must change a KDE config file to point to our theme.

set_kde_wallpaper_as_root() {
    sed -i "s/wallpaper=.*/wallpaper=$PACKAGE/" /home/*/.kde/share/config/plasma-desktop-appletsrc
}


# 2.2 Ksplash
#
# Two files in the users home directory may still activate a former
# Ksplash theme:
#
# $HOME/.kde/share/config/startupconfig.
# $HOME/.kde/share/config/ksplashrc
#
# We have to update these settings in order to point to our theme.

set_ksplash_theme_as_root() {
    sed -i "s/ksplashrc_ksplash_theme=.*/ksplashrc_ksplash_theme=$PACKAGE/" /home/*/.kde/share/config/startupconfig;
    sed -i "s/ksplashrc_ksplash_engine=.*/ksplashrc_ksplash_engine=KSplashX/" /home/*/.kde/share/config/startupconfig;
    sed -i "s/Theme=.*/Theme=$PACKAGE/" /home/*/.kde/share/config/ksplashrc;
    sed -i "s/Engine=.*/Engine=KSplashX/" /home/*/.kde/share/config/ksplashrc;
	
# The Makefile of desktop-theme-kit already put a symlink to the 
# login-picture into Ksplashs "/../1920x1080" directory. Nevertheless 
# we test if imagemagick is available. If so, we resize and crop the
# login-picture to a variety of different resolutions, maintaining 
# the aspect-ratio. Otherwise KSplash may distort the picture.
	
if [ -x /usr/bin/convert ]; then
echo "Please wait just a minute, I am calculating the resolutions for KSplash...";
		
convert /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png -resize 1024x768^ -gravity center -extent 1024x768 /usr/share/kde4/apps/ksplash/Themes/$THEME/1024x768/background.png;

echo "Imagemagick resized 1 of 7 KSplash background pictures.";
		
convert /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png -resize 1280x1024^ -gravity center -extent 1280x1024 /usr/share/kde4/apps/ksplash/Themes/$THEME/1280x1024/background.png;

echo "Imagemagick resized 2 of 7 KSplash background pictures.";

convert /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png -resize 1280x800^ -gravity center -extent 1280x800 /usr/share/kde4/apps/ksplash/Themes/$THEME/1280x800/background.png;

echo "Imagemagick resized 3 of 7 KSplash background pictures.";
				
convert /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png -resize 1366x768^ -gravity center -extent 1366x768 /usr/share/kde4/apps/ksplash/Themes/$THEME/1366x768/background.png;

echo "Imagemagick resized 4 of 7 KSplash background pictures.";
				
convert /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png -resize 1600x1200^ -gravity center -extent 1600x1200 /usr/share/kde4/apps/ksplash/Themes/$THEME/1600x1200/background.png;

echo "Imagemagick resized 5 of 7 KSplash background pictures.";

# We delete the symlink "/../1920x1080/@background.png" and resize the
# login-picture to 1920x1080px. It should already be 1920x1080, but it
# won't harm to make sure.
		
rm -f /usr/share/kde4/apps/ksplash/Themes/$THEME/1920x1080/background.png;

convert /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png -resize 1920x1080^ -gravity center -extent 1920x1080 /usr/share/kde4/apps/ksplash/Themes/$THEME/1920x1080/background.png;

echo "Imagemagick resized 6 of 7 KSplash background pictures.";
		
convert /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png -resize 1920x1200^ -gravity center -extent 1920x1200 /usr/share/kde4/apps/ksplash/Themes/$THEME/1920x1200/background.png;

echo -e "Imagemagick resized 7 of 7 KSplash background pictures. \nThanks for your patience!";

fi
}


# 2.3 KDM
#
# If the user changed the KDM theme manually in KDE systemsettings, 
# the changes have been saved to the file "/etc/kde4/kdm/kdmrc" and 
# overwritten the line: 
#
# Theme=@@@ToBeReplacedByDesktopBase@@@
#
# This line configured an override for the Debian KDM configuration.
# If present, /etc/init.d/kdm will create the KDM theme configuration
# in /var/run/kdm/kdmrc, using the values of the file with the highest
# priority in /etc/default/kdm.d (normally "10_desktop-base"). 
#
# Unfortunately it does not seem possible to set the value in 
# /etc/kde4/kdm/kdmrc back to @@@ToBeReplacedByDesktopBase@@@ without
# crashing KDM at logout. 
#
# So we play it safe and just point the configuration to our theme.

set_kdm_theme() {
if [ -f /etc/kde4/kdm/kdmrc ]; then
	sed -i "/@@@ToBeReplacedByDesktopBase@@@/!s/^Theme=.*/Theme=\/usr\/share\/kde4\/apps\/kdm\/themes\/$PACKAGE/" /etc/kde4/kdm/kdmrc
fi
if [ -f /var/run/kdm/kdmrc ]; then
	sed -i "s/^Theme=.*/Theme=\/usr\/share\/kde4\/apps\/kdm\/themes\/$PACKAGE/" /var/run/kdm/kdmrc
fi
}


# 3. lightdm

set_lightdm() {
if [ -f /etc/lightdm/lightdm-gtk-greeter.conf ]; then
sed -i "s/background=.*/background=\/usr\/share\/images\/desktop-base\/desktop-login/" /etc/lightdm/lightdm-gtk-greeter.conf
fi
}

# 4. SLIM
set_slim() {
if [ -f /etc/slim.conf ]; then
	sed -i "s/current_theme.*/current_theme $PACKAGE/" /etc/slim.conf
fi
}


# 5. Plymouth
set_plymouth() {

if [ -d /usr/share/plymouth/themes/$THEME/ ]; then
/bin/cp -f -r /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png /usr/share/plymouth/themes/$THEME/background.png
fi

if [ -x /usr/sbin/plymouth-set-default-theme ]; then
plymouth-set-default-theme $THEME
fi

if [ -x /usr/sbin/update-initramfs ]; then
update-initramfs -u
fi
}


# 6. Grub
set_grub() {
# First of all we copy the login picture to the grub theme directory, 
# so the chosen theme will always provide a grub theme background:

/bin/cp -f -r /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png /usr/share/desktop-theme-$THEME/grub/theme/background.png;

# Then we do some tricky things to avoid that the login-picture will
# be distorted when we use it as background for the grub theme. So we
# look for the resolution set by the line "GRUB_GFXMODE=" in 
# /etc/default/grub. If this line is enabled, we use imagemagick
# to convert the grub-theme background picture to that resolution.

RESOLUTION=$( 
# In the next line we just look for special characters in 
# /etc/default/grub and ignore them:
    for i in `cat /etc/default/grub  | sed -e '/\[/d' | sed -e '/\;/d' | sed -e '/\,/d' | sed -e '/\+/d' | sed -e '/\"/d' | sed -e '/\`/d' | grep '^[^#].*'`
# then we read out the searched parameter
    do
    var=`echo "$i" | awk -F"=" '{print $1}'`
    param=`echo "$i" | awk -F"=" '{print $2}'`
    eval $var=$param
    done
    echo $GRUB_GFXMODE | sed 's/\//\\\//g'
    )

# If the line GRUB_GFXMODE in /etc/default/grub is disabled, the above
# will produce an empty variable that we cannot use. So we first test
# if our variable is not empty. Then we use imagemagick to convert 
# the grub-theme background-picture to the correct resoultion.

if [ "$RESOLUTION" ]; then
convert /usr/share/desktop-theme-$THEME/backgrounds/$THEME-login.png -resize $RESOLUTION^ -gravity center -extent $RESOLUTION /usr/share/desktop-theme-$THEME/grub/theme/background.png;
fi

# And as always: update grub
if which update-grub2 > /dev/null ; then
sync            
update-grub2 || true
fi
}



# 7. Update alternatives
#
# The alternatives are cached. An update clears the cache.

set_alternatives_auto() {
    update-alternatives --auto desktop-background;
    update-alternatives --auto desktop-login
}




# ---------
# UNINSTALL
# ---------
# The uninstall procedures should be run after the desktop-theme-
# package has been uninstalled.

# 1. Gnome

reset_gnome_wallpaper_as_root() {
    rm -f /etc/xdg/autostart/$PACKAGE.desktop;
    find /home -name ".$PACKAGE.id" -delete
}


# 2. KDE 
#
# 2.1 KDE Wallpaper
#
# Note: This won't be necessary for Jessy.

reset_kde_wallpaper_as_root() {
    sed -i "s/wallpaper=.*/wallpaper=$DEBIAN_DEFAULT/" /home/*/.kde/share/config/plasma-desktop-appletsrc 2>/dev/null
}

# 2.2 KSplash
#
# Our theme and the Debian default theme both use the KSplashX 
# engine. So we do not touch the engine configuration.

reset_ksplash_theme_as_root() {
    sed -i "s/ksplashrc_ksplash_theme=$PACKAGE/ksplashrc_ksplash_theme=$DEBIAN_DEFAULT/" /home/*/.kde/share/config/startupconfig 2>/dev/null;
    sed -i "s/Theme=$PACKAGE/Theme=$DEBIAN_DEFAULT/" /home/*/.kde/share/config/ksplashrc 2>/dev/null;

# We remove all the images in different resolutions, that we had 
# imagemagick create when we installed the theme for KSplash.
rm /usr/share/kde4/apps/ksplash/Themes/$THEME/1024x768/background.png;
rm /usr/share/kde4/apps/ksplash/Themes/$THEME/1280x1024/background.png;
rm /usr/share/kde4/apps/ksplash/Themes/$THEME/1280x800/background.png;
rm /usr/share/kde4/apps/ksplash/Themes/$THEME/1366x768/background.png;
rm /usr/share/kde4/apps/ksplash/Themes/$THEME/1600x1200/background.png;
rm /usr/share/kde4/apps/ksplash/Themes/$THEME/1920x1080/background.png;
rm /usr/share/kde4/apps/ksplash/Themes/$THEME/1920x1200/background.png;
}


# 2.3 KDM
#
# We reset /etc/kde4/kdm/kdmrc to the Debian default theme. As 
# explained above, we avoid setting /etc/kde4/kdm/kdmrc to the 
# original line "Theme=@@@ToBeReplacedByDesktopBase@@@". If we would 
# not, KDM would not find a valid theme at logout and crash. If you 
# really want to reset everything EXACTLY to how it was before, then 
# set the value and reboot afterwards. 

reset_kdm_theme() {
if [ -f /etc/kde4/kdm/kdmrc ]; then
    sed -i '/@@@ToBeReplacedByDesktopBase@@@/!s/^Theme=.*/Theme=\/usr\/share\/kde4\/apps\/kdm\/themes\/$DEBIAN_DEFAULT/' /etc/kde4/kdm/kdmrc
fi
if [ -f /var/run/kdm/kdmrc ]; then
    sed -i 's/^Theme=.*/Theme=\/usr\/share\/kde4\/apps\/kdm\/themes\/$DEBIAN_DEFAULT/' /var/run/kdm/kdmrc
fi
}


# 3. lightdm

reset_lightdm() {
if [ -f /etc/lightdm/lightdm-gtk-greeter.conf ]; then
    sed -i "s/background=.*/background=\/usr\/share\/images\/desktop-base\/login-background.svg/" /etc/lightdm/lightdm-gtk-greeter.conf
fi
}


# 4. SLIM
reset_slim() {
if [ -f /etc/slim.conf ]; then
	sed -i "s/current_theme.*/current_theme debian-$DEBIAN_DEFAULT/" /etc/slim.conf;
fi
}

# 5. Plymouth

reset_plymouth() {
if [ -f /usr/share/plymouth/themes/$THEME/background.png ]; then
       rm /usr/share/plymouth/themes/$THEME/background.png
fi
}



# 6. Grub
reset_grub() {
if [ -f /usr/share/desktop-theme-$THEME/grub/theme/background.png ]; then
	rm /usr/share/desktop-theme-$THEME/grub/theme/background.png
fi
}



# 7. Reset alternatives
reset_alternatives_auto() {
    update-alternatives --auto desktop-background;
}
# The alternative "desktop-login" is part of the desktop-theme-
# package and will be uninstalled anyway.




# ------------
# Script stuff
# ------------

install_theme_for_all_users() {
    choose_theme
    clear_wallpaper_cache_as_root
    set_alternatives_auto
    set_gnome_wallpaper_as_root
    set_kde_wallpaper_as_root
    set_ksplash_theme_as_root
    set_kdm_theme
    set_lightdm
    set_slim
    set_plymouth
    set_grub
	echo -e "The desktop-theme has been successfully updated. \nPlease re-login to see the changes."
}

uninstall_theme_for_all_users() {
    reset_gnome_wallpaper_as_root
    reset_kde_wallpaper_as_root
    reset_ksplash_theme_as_root
    reset_kdm_theme
    reset_lightdm
    reset_slim
    reset_plymouth
    reset_grub
    clear_wallpaper_cache_as_root
    reset_alternatives_auto
}


# Displays the current help
usage() {
    cat <<EOF
Desktop theme utility

Updates user and system desktop default theme and artwork.

Usage:  $0 [-i|-r]
        $0 [-h|--help|-?]

Where:
    -i
        Installs the theme

    -r
        Removes the theme

    -h
    -?
    --help
        Displays the current help text and exit

EOF
}

# Main
argc="$#"
argv="$1"

if [ $argc -eq 0 ] ; then usage ; exit 0; fi

while [ $# -gt 0 ]; do
    case $1 in
        -i)
            shift
            install_theme_for_all_users
        ;;
        
        -r)
            shift
            uninstall_theme_for_all_users
        ;;

        *)
            usage
        ;;
    esac
    shift
done

